language: python

sudo: true
fast_finish: true

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install Cython
  - pip install -r requirements.txt
  - pip install .

script:
  - nosetests

after_success:
  - coveralls

branches:
  only:
    - master
    - develop

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
